[[redirects]]
  from = "/about"
  to = "http://hello.kellyluo.me/"
  status = 301
  force = false
  query = {path = ":path"}


[[redirects]]
  from = "/resume"
  to = "http://resume.kellyluo.me/"
  status = 301
  force = false
  query = {path = ":path"}