[[redirects]]
  from = "https://hello.kellyluo.me"
  to = "https://kellyluo.me/about"
  status = 301!
  force = true


[[redirects]]
  from = "https://resume.kellyluo.me"
  to = "https://kellyluo.me/resume"
  status = 301!
  force = true