[[redirects]]
  from = "http://hello.kellyluo.me/*"
  to = "https://kellyluo.me/about/"
  status = 301
  force = true
  query = {path = ":path"}


[[redirects]]
  from = "https://resume.kellyluo.me/*"
  to = "https://kellyluo.me/resume"
  status = 301
  force = true
  query = {path = ":path"}