[[redirects]]
  from = "http://hello.kellyluo.me"
  to = "https://kellyluo.me/about"
  status = 200
  force = true


[[redirects]]
  from = "https://resume.kellyluo.me"
  to = "https://kellyluo.me/resume"
  status = 200
  force = true