[[redirects]]
  from = "http://hello.kellyluo.me/*"
  to = "/about"
  status = 301
  force = true
  query = {path = ":path"}


[[redirects]]
  from = "https://resume.kellyluo.me/*"
  to = "/resume"
  status = 301
  force = true
  query = {path = ":path"}